version: "2.1"
services:
  nginx-react:
     image: reactapp:latest
     container_name: saveItApp
     build:
       context: .
       dockerfile: Dockerfile
     ports:
       - 3000:3000
     environment:
       NODE_ENV: production