export const SET_WALLET_DATA = 'SET_WALLET_DATA';
export const SET_PRODUCT_FOR_BUYING = 'SET_PRODUCT_FOR_BUYING';
export const ORDERS_BY_ADDRESS = 'ORDERS_BY_ADDRESS';
export const LOADER = 'LOADER';
